# Generated by Django 6.0.4 on 2026-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_remove_producto_categoria_remove_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
