# Generated by Django 6.0.4 on 2026-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0004_alter_perfil_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('Única', 'Única')], default='M', max_length=10),
        ),
    ]
