# Generated by Django 6.0.4 on 2026-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0005_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
    ]
