# Generated by Django 6.0.4 on 2026-04-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0007_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='pieza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_uniforme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
