# Generated by Django 6.0.4 on 2026-04-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0008_producto_genero_producto_pieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_temp',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
