# Generated by Django 6.0.4 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0009_perfil_email_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='username_temp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
