"""
Django settings for zeus project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-g5y**e3ksw+-t34ggc4&-8rccl#6y4$s-#cvw58v5^_$51i=z2'


DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppPagina',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zeus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zeus.wsgi.application'


# base de datos DataBase
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# validación contraseña
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Dejamos la lista vacía para permitir registros rápidos y simples sin restricciones
AUTH_PASSWORD_VALIDATORS = []


# Internacionalizacion
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Redirecciones para autenticación
LOGIN_REDIRECT_URL = 'principal'
LOGOUT_REDIRECT_URL = 'index'

# Hacer que la sesión expire al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#Expira en 20 minutos de inactividad (en segundos)
SESSION_COOKIE_AGE = 1200 

# Configuración de Email para Producción (Envío real)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'giraldorochad@gmail.com'  # Reemplaza con tu correo
EMAIL_HOST_PASSWORD = 'cmjy zvql mvhs yjvs'  # Reemplaza con tu Contraseña de Aplicación
DEFAULT_FROM_EMAIL = 'OS Store <giraldorochad@gmail.com>'

# Si usas Gmail, necesitarás generar una "contraseña de aplicación" si tienes la verificación en dos pasos activada.
# Busca en Google "Gmail contraseña de aplicación" para más información.


# Configuración de archivos multimedia (Imágenes de productos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
